- name: make some directory (test)
  sudo: true
  file: path=/testf state=directory

# Create nagios users and groups.
- name: create nagios group
  sudo: true
  group: >
    gid=3000
    name=nagios

- name: create nagcmd group
  sudo: true
  group: >
    gid=3001
    name=nagcmd

- name: create nagios user
  sudo: true
  user: >
    uid=3000
    group=nagios
    groups=nagcmd
    name=nagios
    home=/usr/local/nagios
    comment="Nagios Admin"

- name: add user www-data to nagcmd group
  sudo: true
  user: >
    groups=nagcmd
    name=www-data

# Update and install dependent packages.
- name: install nrpe packages
  sudo: true
  apt: pkg={{ item }} state=present force=true update_cache=yes
  with_items: nagios_nrpe_packages

- name: Add ip's to npre.cfg
  sudo: true
  lineinfile: dest=/etc/nagios/nrpe.cfg regexp='^allowed_hosts=127\.0\.0\.1' insertafter='allowed_hosts=127.0.0.1'  line=',{{nagios_host_ip}},{{nagios_nrpe_ip}}' state=present
  notify: restart nrpe

- tasks:
  include: elasticsearch.yml